repos:
  - repo: git://github.com/PyCQA/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
