language: python
python: 3.6
env:
  global:
  - DB_HOST=localhost
  - DB_NAME=edge_dev
  - DB_USER=root
  - DB_PASSWORD=''
  - CELERY_CONFIG_MODULE=server.settings
  - NCBI_BIN_DIR=/usr/bin
  - PRIMER3_BIN=/usr/bin/primer3_core
  - PRIMER3_CONFIG_DIR=/etc/primer3_config/
  matrix:
  - TARGET=test-ci
  - TARGET=flake8
addons:
  apt:
    packages:
    - ncbi-blast+
    - primer3
services: mysql
cache:
  pip: true
before_install:
- npm install --global bower
- mysql -e "CREATE DATABASE $DB_NAME;"
install:
- pip install --requirement requirements.txt
- pip install --editable .
script:
- make $TARGET
deploy:
  provider: pypi
  user: ginkgodev
  distributions: sdist bdist_wheel
  password:
    secure: A/Pq1Jkuueu8d8a0SaQiErWWhaQFVCP8CgJO4XOjrlCXKWaXjDDPs0a+eXiwV/xRQPw6TF6NYWgrxjNHshDbADbrbnWtCCN0nL72CoUtj1E8Kk2nUpUyF4SKuYAErxKdD1gzRZS1zp3vCS7MxUzChEQyy5Q1foDgIBBuLb0x+8NFLKlHhJoUel3ClMO8HdJwpBpChlzRd9WuWWVKeA1l1/clpLpBt3GhWB4iTRgpMwBvTEXGdadbcoWaQ0FKT4l5Wfn5inJ5SfyyNCN4jYLsxn+KDfo2MS2g3pEko+7wtRIv9RgHWlsuvZecdhfBwLjo5/7vVm8b+RJpg6eqggqrkB6v55uB1U1nVOtXaeBJDwtzHYf/ullEo5y9szIde1j4nIRK3mzsRPHrApDd/kQM+MBwJASL6LvE3R0ea0mySwvaEzoGbPs5lvTdRJ3p4iaVpY74THWS7EOK8XHoI0NyUmmMkoUT0itj6DbudANqyAEaKX79xm9g9+PL9VfFCQc8nxj5Jh80YTF2mVgC4HZoqlLbbOv2SPlcRoINp0Vfene2jM+10GXshoj0L0k9bh/T3ITcfbExDKDgwAURFCRhJ4q5wL4hGSk/Ekl7sl6cqEtET44f0boPSGWQrfib13ltlorC+losE0HLDyulBUa3Xu1sTce0oFs39SqO6cvjmms=
  on:
    tags: true
    repo: ginkgobioworks/edge
